# Generated by Django 5.2.1 on 2025-05-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('txt', 'Text File'), ('html', 'HTML File'), ('xml', 'XML File')], max_length=4)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
